Repository microsoft/vscode-python-debugger, pull requests merged in 2023-06, with the labels that each got.

#16 Update `@vscode/extension-telemetry`
  package-lock.json
  package.json
Labels: debt

#15 Add GitHub labels
  .flake8
  .github/actions/build-vsix/action.yml
  .github/actions/lint/action.yml
  .github/dependabot.yml
  .github/release.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/issue-labels.yml
  .github/workflows/pr-check.yml
  .github/workflows/pr-labels.yml
  .github/workflows/push-check.yml
  .vscode/settings.json
  noxfile.py
  package-lock.json
  package.json
  src/test/unittest/hooks/childProcessAttachHandler.unit.test.ts
Labels: debt

#25 Fix push check tests
  .github/workflows/push-check.yml
Labels: debt

#26 Add xvfb for linux tests
  .github/workflows/push-check.yml
Labels: debt

#28 Engineering - add TSAOptions
  build/azure-pipeline.stable.yml
Labels: no-changelog

#29 Fix package version
  .vscode/launch.json
  .vscode/settings.json
  .vscode/tasks.json
  noxfile.py
  package-lock.json
  package.json
  requirements.txt
  src/extension/debugger/configuration/resolvers/launch.ts
  src/extension/telemetry/index.ts
  src/test/unittest/index.ts
  src/test/unittests.ts
  tsconfig.json
  webpack.config.js
Labels: no-changelog

#30 Fix error checking python version
  src/extension/debugger/adapter/factory.ts
Labels: bug

#32 Adopt lifecycle managed by parent
  src/extension/debugger/hooks/childProcessAttachService.ts
  src/test/unittest/hooks/childProcessAttachService.unit.test.ts
Labels: bug

#47 Update name in dynamic config
  src/extension/debugger/configuration/dynamicdebugConfigurationService.ts
Labels: bug
