Repository microsoft/vscode-python-debugger, pull requests merged in 2024-02, with the labels that each got.

#196 Merge release in main
  build/azure-pipeline.stable.yml
Labels: no-changelog

#210 Update some minor debt issues
  package-lock.json
  package.json
Labels: debt

#214 Open browser after launching
  package.json
  src/extension/debugger/configuration/resolvers/base.ts
  src/extension/debugger/configuration/resolvers/launch.ts
  src/extension/telemetry/index.ts
  src/test/unittest/configuration/resolvers/launch.unit.test.ts
Labels: feature-request

#218 Adding note to use pre-releases for older versions
  README.md
Labels: documentation, debt

#228 Do not create config when esc is hit
  src/extension/debugger/configuration/providers/djangoLaunch.ts
  src/extension/debugger/configuration/providers/fastapiLaunch.ts
  src/extension/debugger/configuration/providers/flaskLaunch.ts
  src/extension/debugger/configuration/providers/moduleLaunch.ts
  src/extension/debugger/configuration/providers/pyramidLaunch.ts
  src/extension/debugger/configuration/providers/remoteAttach.ts
  src/test/unittest/configuration/providers/djangoLaunch.unit.test.ts
  src/test/unittest/configuration/providers/fastapiLaunch.unit.test.ts
  src/test/unittest/configuration/providers/flaskLaunch.unit.test.ts
  src/test/unittest/configuration/providers/moduleLaunch.unit.test.ts
  src/test/unittest/configuration/providers/pyramidLaunch.unit.test.ts
  src/test/unittest/configuration/providers/remoteAttach.unit.test.ts
Labels: bug

#229 Add auto start browser as default value
  src/extension/debugger/configuration/providers/djangoLaunch.ts
  src/extension/debugger/configuration/providers/flaskLaunch.ts
  src/test/unittest/configuration/providers/djangoLaunch.unit.test.ts
  src/test/unittest/configuration/providers/flaskLaunch.unit.test.ts
Labels: feature-request

#234 Update README.md
  README.md
Labels: no-changelog

#236 Update branch for python 3.7
  README.md
  src/extension/debugger/configuration/providers/djangoLaunch.ts
  src/extension/debugger/configuration/providers/fastapiLaunch.ts
  src/extension/debugger/configuration/providers/flaskLaunch.ts
  src/extension/debugger/configuration/providers/moduleLaunch.ts
  src/extension/debugger/configuration/providers/pyramidLaunch.ts
  src/extension/debugger/configuration/providers/remoteAttach.ts
  src/test/unittest/configuration/providers/djangoLaunch.unit.test.ts
  src/test/unittest/configuration/providers/fastapiLaunch.unit.test.ts
  src/test/unittest/configuration/providers/flaskLaunch.unit.test.ts
  src/test/unittest/configuration/providers/moduleLaunch.unit.test.ts
  src/test/unittest/configuration/providers/pyramidLaunch.unit.test.ts
  src/test/unittest/configuration/providers/remoteAttach.unit.test.ts
Labels: no-changelog

#238 bumb-release-2024.2
  package-lock.json
  package.json
Labels: no-changelog

#239 bump release for py3.7 branch
  package-lock.json
  package.json
Labels: no-changelog

#240 bumb dev version
  package-lock.json
  package.json
Labels: no-changelog

#242 Finalized release 2024.2
  package-lock.json
  package.json
Labels: no-changelog

#217 Fix typos
  README.md
  package.json
  src/extension/common/persistentState.ts
  src/extension/debugger/configuration/launch.json/updaterServiceHelper.ts
  src/extension/debugger/helpers/protocolParser.ts
  src/extension/extensionInit.ts
  src/extension/telemetry/index.ts
  src/test/constants.ts
  src/test/initialize.ts
  src/test/unittest/configuration/launch.json/updaterServerHelper.unit.test.ts
  src/test/unittest/extensionInit.unit.test.ts
  src/test/unittest/utils.ts
Labels: debt
