Repository microsoft/vscode-python-debugger, pull requests merged in 2024-01, with the labels that each got.

#124 Update branch for debugpy 1.5.1 with last changes in main
  .github/actions/build-vsix/action.yml
  .github/actions/lint/action.yml
  .github/workflows/codeql-analysis.yml
  .github/workflows/issue-labels.yml
  .github/workflows/pr-check.yml
  .github/workflows/pr-labels.yml
  .github/workflows/push-check.yml
  .vscodeignore
  README.md
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  debugpy_info.json
  noxfile.py
  package-lock.json
  package.json
  package.nls.json
  src/extension/common/utils/localize.ts
  src/extension/debugger/adapter/outdatedDebuggerPrompt.ts
  src/extension/debugger/adapter/remoteLaunchers.ts
  src/extension/debugger/configuration/dynamicdebugConfigurationService.ts
  src/extension/debugger/configuration/providers/djangoLaunch.ts
  src/extension/debugger/configuration/providers/fastapiLaunch.ts
  src/extension/debugger/configuration/providers/fileLaunch.ts
  src/extension/debugger/configuration/providers/fileLaunchWithArgs.ts
  src/extension/debugger/configuration/providers/flaskLaunch.ts
  src/extension/debugger/configuration/providers/moduleLaunch.ts
  src/extension/debugger/configuration/providers/pidAttach.ts
  src/extension/debugger/configuration/providers/pyramidLaunch.ts
  src/extension/debugger/configuration/providers/remoteAttach.ts
  src/extension/debugger/configuration/resolvers/attach.ts
  src/extension/debugger/configuration/resolvers/launch.ts
  src/extension/debugger/debugPort/portAttributesProvider.ts
  src/extension/extension.ts
  src/extension/extensionInit.ts
  src/extension/telemetry/constants.ts
  src/extension/telemetry/index.ts
  src/test/common.ts
  src/test/unittest/adapter/factory.unit.test.ts
  src/test/unittest/adapter/remoteLaunchers.unit.test.ts
  src/test/unittest/configuration/launch.json/updaterServerHelper.unit.test.ts
  src/test/unittest/configuration/providers/djangoLaunch.unit.test.ts
  src/test/unittest/configuration/providers/fastapiLaunch.unit.test.ts
  src/test/unittest/configuration/providers/fileLaunch.unit.test.ts
  src/test/unittest/configuration/providers/fileLaunchWithArgs.unit.test.ts
  src/test/unittest/configuration/providers/flaskLaunch.unit.test.ts
  src/test/unittest/configuration/providers/moduleLaunch.unit.test.ts
  src/test/unittest/configuration/providers/pidAttach.unit.test.ts
  src/test/unittest/configuration/providers/pyramidLaunch.unit.test.ts
  src/test/unittest/configuration/providers/remoteAttach.unit.test.ts
  src/test/unittest/configuration/resolvers/attach.unit.test.ts
  src/test/unittest/configuration/resolvers/launch.unit.test.ts
  src/test/unittest/extensionInit.unit.test.ts
  src/test/unittest/hooks/childProcessAttachHandler.unit.test.ts
  src/test/unittest/hooks/childProcessAttachService.unit.test.ts
  vscode.proposed.portsAttributes.d.ts
Labels: debt

#140 Register port in port attribute provider
  src/extension/debugger/debugPort/portAttributesProvider.ts
  src/extension/debugger/hooks/constants.ts
  src/extension/debugger/hooks/debugpySocketsHandler.ts
  src/extension/extensionInit.ts
Labels: feature-request

#185 update test-electron
  package-lock.json
  package.json
Labels: no-changelog

#184 Add version support table to README
  README.md
Labels: documentation, no-changelog

#186 bump release 2024.0
  package-lock.json
  package.json
Labels: no-changelog

#187 Bump dev version 2024.1
  package-lock.json
  package.json
Labels: no-changelog

#189 Finalized release 2024.0
  build/azure-pipeline.stable.yml
  package-lock.json
  package.json
Labels: no-changelog
