Repository microsoft/vscode-python-debugger, pull requests merged in 2024-12, with the labels that each got.

#513 Don't show automatic debug config in virtual workspace
  package-lock.json
  package.json
Labels: bug

#516 add basic workflows
  .github/workflows/community-feedback-auto-comment.yml
  .github/workflows/info-needed-closer.yml
Labels: debt

#517 Update issue-labels.yml
  .github/workflows/issue-labels.yml
Labels: debt

#519 Update version for release
  package-lock.json
  package.json
Labels: no-changelog

#534 Create commands.json
  .github/commands.json
Labels: debt

#536 Update to 1.8.11
  debugpy_info.json
Labels: feature-request
