Repository microsoft/vscode-python-debugger, pull requests merged in 2024-04, with the labels that each got.

#299 bump release 2024.4
  package-lock.json
  package.json
Labels: no-changelog

#300 bump dev version
  package-lock.json
  package.json
Labels: no-changelog

#278 Add api and send debugpy path
  src/extension/api.ts
  src/extension/apiTypes.ts
  src/extension/extension.ts
  src/extension/extensionInit.ts
  tsconfig.json
Labels: debt

#305 Fix code annotations
  src/extension/debugger/hooks/debugpySocketsHandler.ts
  src/extension/extensionInit.ts
  src/test/runTest.ts
  src/test/unittest/adapter/adapter.test.ts
  src/test/unittest/adapter/factory.unit.test.ts
  src/test/unittest/configuration/resolvers/base.unit.test.ts
  tsconfig.json
Labels: no-changelog

#317 Show variables in hex
  package.json
  src/extension/common/utils/localize.ts
  src/extension/debugger/visualizers/inlineHexDecoder.ts
  src/extension/extensionInit.ts
  vscode.proposed.debugVisualization.d.ts
Labels: feature-request

#319 Use consoleName in launch.json file
  package.json
  src/extension/debugger/configuration/resolvers/base.ts
  src/extension/debugger/configuration/resolvers/launch.ts
  src/test/unittest/configuration/resolvers/attach.unit.test.ts
  src/test/unittest/configuration/resolvers/launch.unit.test.ts
Labels: feature-request

#267 Fix debugger attach to process when running on WSL
  src/extension/common/process/rawProcessApis.ts
Labels: bug

#330 bumb release 2024.6
  package-lock.json
  package.json
Labels: no-changelog

#331 bump dev version 2024.7
  package-lock.json
  package.json
Labels: no-changelog
