Repository microsoft/vscode-python-debugger, pull requests merged in 2024-03, with the labels that each got.

#244 chore: add APIScan field
  build/azure-pipeline.stable.yml
Labels: no-changelog

#253 Update use of python extension environment api
  package-lock.json
  package.json
  src/extension/common/python.ts
  src/extension/common/pythonTypes.ts
  src/extension/debugger/adapter/factory.ts
  src/test/runTest.ts
  src/test/unittest/adapter/factory.unit.test.ts
Labels: bug

#264 Improve debug config in django
  src/extension/common/multiStepInput.ts
  src/extension/common/utils/async.ts
  src/extension/common/utils/localize.ts
  src/extension/debugger/configuration/debugConfigurationService.ts
  src/extension/debugger/configuration/dynamicdebugConfigurationService.ts
  src/extension/debugger/configuration/providers/djangoLaunch.ts
  src/extension/debugger/configuration/providers/providerQuickPick/djangoProviderQuickPick.ts
  src/extension/debugger/configuration/providers/providerQuickPick/providerQuickPick.ts
  src/extension/debugger/configuration/providers/providerQuickPick/types.ts
  src/extension/debugger/configuration/utils/configuration.ts
  src/extension/telemetry/index.ts
  src/test/unittest/configuration/providers/djangoLaunch.unit.test.ts
  src/test/unittest/configuration/providers/providerQuickPick/djangoProviderQuickPick.unit.test.ts
Labels: feature-request

#276 Improve debug config in flask
  src/extension/common/utils/localize.ts
  src/extension/debugger/configuration/providers/flaskLaunch.ts
  src/extension/debugger/configuration/providers/providerQuickPick/flaskProviderQuickPick.ts
  src/extension/debugger/configuration/utils/configuration.ts
  src/test/unittest/configuration/providers/flaskLaunch.unit.test.ts
  src/test/unittest/configuration/providers/providerQuickPick/flaskProviderQuickPick.unit.test.ts
Labels: feature-request

#277 Fix platform-specific error
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
Labels: bug

#292 Fix input error in django and flask pickers
  package-lock.json
  package.json
  src/extension/common/multiStepInput.ts
  src/extension/debugger/configuration/providers/providerQuickPick/djangoProviderQuickPick.ts
  src/extension/debugger/configuration/providers/providerQuickPick/flaskProviderQuickPick.ts
  src/extension/debugger/configuration/providers/providerQuickPick/providerQuickPick.ts
  tsconfig.json
Labels: bug
