Repository microsoft/vscode-python-debugger, pull requests merged in 2025-01, with the labels that each got.

#550 Support the clientOS property in VS code
  package.json
  src/extension/debugger/configuration/resolvers/attach.ts
  src/extension/debugger/configuration/resolvers/base.ts
  src/extension/debugger/configuration/resolvers/launch.ts
Labels: debt

#559 add contributing.md
  contributing.md
Labels: debt

#557 Configless debug
  .vscode/launch.json
  bundled/scripts/noConfigScripts/debugpy
  bundled/scripts/noConfigScripts/debugpy.bat
  bundled/scripts/noConfigScripts/debugpy.fish
  bundled/scripts/noConfigScripts/debugpy.ps1
  src/extension/extensionInit.ts
  src/extension/noConfigDebugInit.ts
  src/extension/utils.ts
  src/test/unittest/noConfigDebugInit.unit.test.ts
Labels: feature-request

#566 add in description for no-config debug environment variable edits
  src/extension/noConfigDebugInit.ts
Labels: debt

#565 disable extra output for no config debug
  src/extension/noConfigDebugInit.ts
  src/test/unittest/noConfigDebugInit.unit.test.ts
Labels: bug

#570 include debugpy in description
  src/extension/noConfigDebugInit.ts
Labels: debt

#577 add link to wiki
  src/extension/noConfigDebugInit.ts
Labels: bug

#576 switch to using python3 in the script for no-config debugging
  bundled/scripts/noConfigScripts/debugpy
  bundled/scripts/noConfigScripts/debugpy.fish
  bundled/scripts/noConfigScripts/debugpy.ps1
Labels: bug
