Repository microsoft/vscode-python-debugger, pull requests merged in 2025-05, with the labels that each got.

#705 Bump 2025.8
  package-lock.json
  package.json
  src/extension/debugger/adapter/factory.ts
Labels: no-changelog

#706 Bump 2025.9.0 dev
  package-lock.json
  package.json
Labels: no-changelog

#709 chore: lock down workflows
  .github/workflows/codeql-analysis.yml
  .github/workflows/pr-check.yml
  .github/workflows/pr-labels.yml
  .github/workflows/push-check.yml
  .vscode/settings.json
Labels: no-changelog

#713 expose getDebugpyPackagePath
  src/extension/extension.ts
Labels: feature-request

#692 Fix `TypeError` from trying to read directory
  src/extension/noConfigDebugInit.ts
  src/test/unittest/noConfigDebugInit.unit.test.ts
Labels: bug
