Repository microsoft/vscode-python-debugger, pull requests merged in 2025-03, with the labels that each got.

#643 bump version to 2025.2.0 for release
  package-lock.json
  package.json
Labels: debt

#644 bump to version 2025.3.0-dev
  package-lock.json
  package.json
Labels: debt

#646 respect existing serverReadyAction in launch config
  src/extension/debugger/configuration/resolvers/launch.ts
  src/test/unittest/configuration/resolvers/launch.unit.test.ts
Labels: bug

#650 switch to warning if launch.json missing version
  src/extension/debugger/configuration/launch.json/launchJsonReader.ts
Labels: bug

#654 update to release version 2025.4
  package-lock.json
  package.json
Labels: debt

#657 update to version 2025.5.0-dev
  package-lock.json
  package.json
Labels: debt

#658 switch to use debug_session.start for no-config debug telemetry
  src/extension/noConfigDebugInit.ts
  src/extension/telemetry/constants.ts
  src/extension/telemetry/index.ts
  src/extension/types.ts
Labels: debt

#653 Update debugpy to latest version
  debugpy_info.json
Labels: debt

#659 clear env var collection before adding new items
  src/extension/noConfigDebugInit.ts
Labels: bug

#660 update to python version 3.9
  .github/actions/build-vsix/action.yml
  .github/actions/lint/action.yml
  .github/workflows/pr-check.yml
  .github/workflows/push-check.yml
  README.md
  build/azure-pipeline.pre-release.yml
  build/azure-pipeline.stable.yml
  requirements.txt
  src/extension/debugger/adapter/factory.ts
Labels: debt

#663 clear env var collection before adding new items (#659)
  src/extension/noConfigDebugInit.ts
Labels: bug

#664 Update release/2025.4.1
  package-lock.json
  package.json
Labels: debt

#684 Bump release 2025.6
  package-lock.json
  package.json
Labels: no-changelog
