Repository microsoft/vscode-python-debugger, pull requests merged in 2025-02, with the labels that each got.

#588 Bump release 2025.0.0
  .github/actions/build-vsix/action.yml
  package-lock.json
  package.json
Labels: no-changelog

#589 bump to 2025.1.0-dev
  package-lock.json
  package.json
Labels: no-changelog

#597 fix no-config debugger env var insertion to be less noisy
  src/extension/noConfigDebugInit.ts
  src/test/unittest/noConfigDebugInit.unit.test.ts
Labels: bug

#602 correct workspace path for mutiroot scenarios no-config debugging
  src/extension/noConfigDebugInit.ts
Labels: no-changelog

#601 fix no-config debugger env var insertion to be less noisy
  src/extension/noConfigDebugInit.ts
  src/test/unittest/noConfigDebugInit.unit.test.ts
Labels: bug

#607 correct workspace path for mutiroot scenarios no-config debugging (#602)
  src/extension/noConfigDebugInit.ts
Labels: bug

#610 fix no-debug ps1 script
  bundled/scripts/noConfigScripts/debugpy.ps1
Labels: bug

#611 fix powershell script for powershell no-config debug
  bundled/scripts/noConfigScripts/debugpy.ps1
Labels: bug

#608 bump release for point release 2025.0.1
  package-lock.json
  package.json
Labels: no-changelog

#585 get launch config from settings.json as fallback
  src/extension/debugger/configuration/launch.json/launchJsonReader.ts
  src/test/unittest/configuration/launch.json/launchJsonReader.unit.test.ts
Labels: bug

#548 Make "args": "${command:pickArgs}" as default debug configuration
  src/extension/debugger/configuration/providers/fileLaunchWithArgs.ts
  src/test/unittest/configuration/providers/fileLaunchWithArgs.unit.test.ts
Labels: bug

#620 fix bug with extension overriding debugpy endpoint
  bundled/scripts/noConfigScripts/debugpy
  bundled/scripts/noConfigScripts/debugpy.bat
  bundled/scripts/noConfigScripts/debugpy.fish
  bundled/scripts/noConfigScripts/debugpy.ps1
  src/extension/noConfigDebugInit.ts
Labels: bug

#628 switch telemetry event owner
  src/extension/telemetry/index.ts
Labels: debt

#629 add telemetry event for no-config debugging
  src/extension/noConfigDebugInit.ts
  src/extension/telemetry/constants.ts
  src/extension/telemetry/index.ts
Labels: debt

#642 fix bug to return empty array when no config exists
  src/extension/debugger/configuration/launch.json/launchJsonReader.ts
  src/test/unittest/configuration/launch.json/launchJsonReader.unit.test.ts
Labels: bug
